### PR TITLE
Fix source url for log4php package

### PR DESCRIPTION
**Pull request by PavelBulat**

### CODE REVIEW

**Comment by PavelBulat** [comment]
Make install failed because source url for log4php package was moved to other git repo (https://issues.apache.org/jira/browse/LOG4PHP-242). I have changed source url

**Comment by duozersk** [comment]
@PavelBulat - looks like you directly changed the `composer.lock` file - if this is the case then we need to implement another solution like the one described in the issue you linked above - adding the entry into the repositories key of `composer.json` and then running `composer update` or smth like this.

**Comment by spleshka** [comment]
Interesting point @duozersk - what sort of drawbacks can be with the current solution?

**Comment by duozersk** [comment]
@spleshka Well, it is not a solution... modifying a line in 7500+ lines of machine-generated file, composer.lock wasn't designed to be modified manually. As for the side effects - it will probably not work after another update of composer dependencies (will be automatically "updated" by composer to a previous value).

**Comment by PavelBulat** [comment]
@duozersk Thanks, I added source repo to composer.json. Now if composer will be update module will be found in added repository and automatically will be add to composer.lock.

**Comment by PavelBulat** [comment]
I think this solution is correct, i did test on master branch. Then i added source repo in composer.json file and did ``composer update --lock``. All modules was installed and lock file was generated.

**Comment by spleshka** [comment]
Thanks for the great review @duozersk - I'm happy now with the solution. Merging & closing the PR.

**Review by spleshka — APPROVED** [review]
Great job @PavelBulat !

**Pull request merged**
